version: "3"
services:
  haproxy:
    image: eeacms/haproxy
    ports:
    - 8080:5000
    - 1936:1936
    depends_on:
    - zeoclient
    environment:
      BACKENDS: zeoclient
      BACKENDS_PORT: 8080
      DNS_ENABLED: "true"

  zeoclient:
    build:
      context: .
      dockerfile: Dockerfile
    image: pkan/app:latest
    depends_on:
    - zeoserver
    environment:
    - ZEO_ADDRESS=zeoserver:8080

  zeoserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: pkan/app:latest
    command: zeo
    volumes:
    - data:/data

volumes:
  data:
